In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Files/museum_visitors.csv", index_col = 0, parse_dates = [0], usecols = [0, 1])
df

            Avila Adobe
Date
2014-01-01        24778
2014-02-01        18976
2014-03-01        25231
2014-04-01        26989
2014-05-01        36883
2014-06-01        29487
2014-07-01        32378
2014-08-01        37680
2014-09-01        28473
2014-10-01        27995
2014-11-01        25691
2014-12-01        18754
2015-01-01        20438
2015-02-01        15578
2015-03-01        21297
2015-04-01        26670
2015-05-01        34383
2015-06-01        30569
2015-07-01        41242
2015-08-01        30700
2015-09-01        20967
2015-10-01        29764
2015-11-01        24483
2015-12-01        21426
2016-01-01        19659
2016-02-01        17378
2016-03-01        20322
2016-04-01        24521
2016-05-01        31728
2016-06-01        23696
2016-07-01        31689
2016-08-01        25987
2016-09-01        22897
2016-10-01        25040
2016-11-01        17760
2016-12-01        20107
2017-01-01        18792
2017-02-01        14035
2017-03-01        20680
2017-04-01        25234
2017-05-01        30029
2017-06-01        22169
2017-07-01        30831
2017-08-01        27009
2017-09-01        23403
2017-10-01        22164
2017-11-01        17629
2017-12-01        18339
2018-01-01        16265
2018-02-01        14718
2018-03-01        19001
2018-04-01        18966
2018-05-01        25173
2018-06-01        22171
2018-07-01        23136
2018-08-01        20815
2018-09-01        21020
2018-10-01        19280
2018-11-01        17163

In [4]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

`parse_dates` — **pandas**da CSV fayldagi **sana (datetime) turidagi ustunlarni avtomatik ravishda sanaga aylantirib beruvchi parametr**.

---

# `parse_dates` nima qiladi?

Agar CSV faylda sana matn ko‘rinishida bo‘lsa, pandas uni oddiy *string* sifatida o‘qiydi:

```
"2014-01"
"2015-06"
"2016-09"
```

`parse_dates=[0]` yozilsa, **1-ustun sanaga aylantiriladi**, ya’ni:

```
2014-01-01   →  Timestamp('2014-01-01')
2015-06-01   →  Timestamp('2015-06-01')
```

In [7]:
df = pd.read_csv("Files/museum_visitors.csv", index_col = 0, parse_dates=[0], usecols = [0, 1])
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [8]:
df['month'] = [i.month for i in df.index]
df.head()

            Avila Adobe  month
Date
2014-01-01        24778      1
2014-02-01        18976      2
2014-03-01        25231      3
2014-04-01        26989      4
2014-05-01        36883      5

In [9]:
df['year'] = [i.year for i in df.index]
df.head()

            Avila Adobe  month  year
Date
2014-01-01        24778      1  2014
2014-02-01        18976      2  2014
2014-03-01        25231      3  2014
2014-04-01        26989      4  2014
2014-05-01        36883      5  2014

Quyida **df.head()** va unga o‘xshash eng ko‘p ishlatiladigan DataFrame ko‘rish metodlari haqida ma'lumot berilgan.

---

# `df.head()`

`df.head()` DataFramening **birinchi 5 qatorini** ko‘rsatadi.

In [19]:
df.head()

            Avila Adobe  month  year
Date
2014-01-01        24778      1  2014
2014-02-01        18976      2  2014
2014-03-01        25231      3  2014
2014-04-01        26989      4  2014
2014-05-01        36883      5  2014

In [20]:
df.head(10)    # birinchi 10 qator

            Avila Adobe  month  year
Date
2014-01-01        24778      1  2014
2014-02-01        18976      2  2014
2014-03-01        25231      3  2014
2014-04-01        26989      4  2014
2014-05-01        36883      5  2014
2014-06-01        29487      6  2014
2014-07-01        32378      7  2014
2014-08-01        37680      8  2014
2014-09-01        28473      9  2014
2014-10-01        27995     10  2014

---

# `df.tail()`

`df.tail()` DataFramening **oxirgi 5 qatorini** chiqaradi.

In [21]:
df.tail()

            Avila Adobe  month  year
Date
2018-07-01        23136      7  2018
2018-08-01        20815      8  2018
2018-09-01        21020      9  2018
2018-10-01        19280     10  2018
2018-11-01        17163     11  2018

In [22]:
df.tail(3)    # oxirgi 3 qator

            Avila Adobe  month  year
Date
2018-09-01        21020      9  2018
2018-10-01        19280     10  2018
2018-11-01        17163     11  2018

---

# `df.info()`

`df.info()` DataFramening **ustunlar tipi**, **bo‘sh qiymatlar soni**, **xotira hajmi** haqida ma’lumot beradi.

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 59 entries, 2014-01-01 to 2018-11-01
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Avila Adobe  59 non-null     int64
 1   month        59 non-null     int64
 2   year         59 non-null     int64
dtypes: int64(3)
memory usage: 1.8 KB

Unda ma’lumot turi (int, float, object, datetime), null qiymatlar bor-yo‘qligi ko‘rinadi.

---

# `df.describe()` — statistik tahlil (faqat sonli ustunlar bilan ishlaydi)

`df.describe()` quyidagilarni beradi:

* count
* mean
* std
* min
* max
* 25%, 50%, 75% percentillar

In [24]:
df.describe()

        Avila Adobe      month         year
count     59.000000  59.000000    59.000000
mean   24061.661017   6.406780  2015.966102
std     5948.997414   3.434704     1.413800
min    14035.000000   1.000000  2014.000000
25%    19469.500000   3.500000  2015.000000
50%    23136.000000   6.000000  2016.000000
75%    27502.000000   9.000000  2017.000000
max    41242.000000  12.000000  2018.000000

---

# `df.sample()` — random qator ko‘rish

DataFramedan tasodifiy qator ko‘rsatadi:

In [13]:
df.sample()

            Avila Adobe  month  year
Date
2015-08-01        30700      8  2015

In [14]:
df.sample(3)    # 3 ta tasodifiy qator

            Avila Adobe  month  year
Date
2014-08-01        37680      8  2014
2015-06-01        30569      6  2015
2018-01-01        16265      1  2018

---

# `df.shape` — o‘lchamlar

Qator va ustunlar sonini beradi:

In [15]:
df.shape
# (qatorlar_soni, ustunlar_soni)

(59, 3)

---

# `df.columns` — ustun nomlari

In [16]:
df.columns

Index(['Avila Adobe', 'month', 'year'], dtype='object')

---

# `df.index` — index qiymatlari

In [17]:
df.index

DatetimeIndex(['2014-01-01', '2014-02-01', '2014-03-01', '2014-04-01',
               '2014-05-01', '2014-06-01', '2014-07-01', '2014-08-01',
               '2014-09-01', '2014-10-01', '2014-11-01', '2014-12-01',
               '2015-01-01', '2015-02-01', '2015-03-01', '2015-04-01',
               '2015-05-01', '2015-06-01', '2015-07-01', '2015-08-01',
               '2015-09-01', '2015-10-01', '2015-11-01', '2015-12-01',
               '2016-01-01', '2016-02-01', '2016-03-01', '2016-04-01',
               '2016-05-01', '2016-06-01', '2016-07-01', '2016-08-01',
               '2016-09-01', '2016-10-01', '2016-11-01', '2016-12-01',
               '2017-01-01', '2017-02-01', '2017-03-01', '2017-04-01',
               '2017-05-01', '2017-06-01', '2017-07-01', '2017-08-01',
               '2017-09-01', '2017-10-01', '2017-11-01', '2017-12-01',
               '2018-01-01', '2018-02-01', '2018-03-01', '2018-04-01',
               '2018-05-01', '2018-06-01', '2018-07-01', '2018-08-01',
               '2018-09-01', '2018-10-01', '2018-11-01'],
              dtype='datetime64[ns]', name='Date', freq=None)

---

# `df.nunique()` — noyob qiymatlar soni

Har bir ustundagi turli qiymatlar sonini beradi:

In [18]:
df.nunique()

Avila Adobe    59
month          12
year            5
dtype: int64

---

| Metod           | Vazifasi             |
| --------------- | -------------------- |
| `df.head()`     | Birinchi qatorlar    |
| `df.tail()`     | Oxirgi qatorlar      |
| `df.info()`     | Texnik diagnostika   |
| `df.describe()` | Statistik tahlil     |
| `df.sample()`   | Random qatorlar      |
| `df.shape`      | O‘lchamlar           |
| `df.columns`    | Ustun nomlari        |
| `df.index`      | Index ro‘yxati       |
| `df.nunique()`  | Noyob qiymatlar soni |

In [16]:
df['year'] = [i.year for i in df.index]
df.head()

            Avila Adobe  month  year
Date
2014-01-01        24778      1  2014
2014-02-01        18976      2  2014
2014-03-01        25231      3  2014
2014-04-01        26989      4  2014
2014-05-01        36883      5  2014

In [19]:
df2 = df.groupby(['month', 'year']).max()
df2.head(12)

            Avila Adobe
month year
1     2014        24778
      2015        20438
      2016        19659
      2017        18792
      2018        16265
2     2014        18976
      2015        15578
      2016        17378
      2017        14035
      2018        14718
3     2014        25231
      2015        21297

`groupby()` va unga o'xshash metodlar pandasda **ma'lumotlarni guruhlash va agregat qilish** uchun ishlatiladi. Quyida bu metodlar va ularning ishlashini tushuntiraman.

---

# 📌 `groupby()` — ma'lumotlarni guruhlash

`groupby()` metodidan foydalanish orqali ma'lumotlarni ma'lum bir ustunlar bo‘yicha guruhlash mumkin. Guruhlashdan so‘ng, har bir guruh uchun agregat funksiyalarini (masalan, **max**, **sum**, **mean**) qo‘llash mumkin.

**Sintaksisi:**

```python
df2 = df.groupby(['month', 'year']).max()
```

Bu yerda:

* **`['month', 'year']`** — **guruhlash** uchun ustunlar. Demak, **oy** va **yil** ustunlari bo‘yicha guruhlash amalga oshadi.
* **`.max()`** — har bir guruh uchun maksimal qiymatni hisoblash.

**Misol:**

```python
df = pd.DataFrame({
    'month': [1, 1, 2, 2, 3, 3],
    'year': [2020, 2020, 2020, 2020, 2020, 2020],
    'value': [10, 20, 30, 40, 50, 60]
})

df2 = df.groupby(['month', 'year']).max()
print(df2)
```

**Natija:**

```
             value
month year        
1     2020     20
2     2020     40
3     2020     60
```

Guruhlashdan so‘ng, har bir yil va oy uchun eng katta qiymat (maksimal) qaytariladi.

---

# 📌 `agg()` — turli agregat funksiyalarini qo‘llash

Agar bir nechta agregat funksiyalarini bir vaqtning o‘zida qo‘llash kerak bo‘lsa, **`agg()`** metodidan foydalanish mumkin.

**Sintaksisi:**

```python
df.groupby(['month', 'year']).agg({
    'value': ['min', 'max', 'mean']
})
```

Bu yerda:

* **`'min'`**, **`'max'`**, va **`'mean'`** — har bir guruh uchun minimum, maksimum, va o‘rtacha qiymatni hisoblash.

**Misol:**

```python
df2 = df.groupby(['month', 'year']).agg({
    'value': ['min', 'max', 'mean']
})
print(df2)
```

**Natija:**

```
             value              
               min max mean
month year                  
1     2020     10  20   15
2     2020     30  40   35
3     2020     50  60   55
```

---

# 📌 `size()` — guruh hajmini hisoblash

Agar har bir guruhdagi elementlar sonini bilmoqchi bo‘lsangiz, **`size()`** metodini qo‘llash mumkin.

**Sintaksisi:**

```python
df.groupby(['month', 'year']).size()
```

Bu metod har bir guruhdagi elementlar sonini qaytaradi.

**Misol:**

```python
df2 = df.groupby(['month', 'year']).size()
print(df2)
```

**Natija:**

```
month  year
1      2020    2
2      2020    2
3      2020    2
dtype: int64
```

---

# 📌 `sum()` — guruhlangan qiymatlar yig‘indisi

Guruhlangan ma'lumotlar bo‘yicha **yig‘indi** olish uchun **`sum()`** metodini ishlatish mumkin.

**Misol:**

```python
df2 = df.groupby(['month', 'year']).sum()
print(df2)
```

**Natija:**

```
             value
month year        
1     2020     30
2     2020     70
3     2020    110
```

---

# 📌 `transform()` — guruhlangan qiymatlarni saqlab qolish

Agar guruhlangan qiymatlarni asl DataFramede saqlab qolish va ular bilan ishlashni istasangiz, **`transform()`** metodini ishlatishingiz mumkin. Bu metod guruhlashdan so‘ng barcha satrlar uchun hisoblangan qiymatlarni asl DataFramede saqlaydi.

**Misol:**

```python
df['max_value'] = df.groupby(['month', 'year'])['value'].transform('max')
print(df)
```

**Natija:**

```
   month  year  value  max_value
0      1  2020     10         20
1      1  2020     20         20
2      2  2020     30         40
3      2  2020     40         40
4      3  2020     50         60
5      3  2020     60         60
```

---

# 📌 `filter()` — guruhlarni filtrlash

**`filter()`** metodini guruhlarni ma'lum bir shartga asoslanib tanlash uchun ishlatishingiz mumkin.

**Misol:**

```python
df2 = df.groupby(['month', 'year']).filter(lambda x: len(x) > 1)
print(df2)
```

Bu yerda, **faqat 1 tadan ko‘p qiymatga ega guruhlar** tanlanadi.

---

# 📌 Xulosa

| Metod         | Vazifasi                                        |
| ------------- | ----------------------------------------------- |
| `groupby()`   | Ma'lumotlarni guruhlash                         |
| `agg()`       | Bir nechta agregat funksiyalarini qo‘llash      |
| `size()`      | Har bir guruhdagi elementlar sonini hisoblash   |
| `sum()`       | Guruhlangan qiymatlarning yig‘indisini olish    |
| `transform()` | Guruhlangan qiymatlarni asl DataFramega saqlash |
| `filter()`    | Guruhlarni filtrlash                            |

Guruhlash metodlari yordamida ma'lumotlarni oson va samarali tahlil qilish mumkin. Agar xohlasangiz, har bir metodga misollar keltirib, batafsil tushuntirish beraman.