In [15]:
from IPython.display import display, HTML

display(HTML("""
<style>
    /* 1. UMUMIY KONTEYNER VA SHRIFT */
    .rendered_html, .jp-RenderedHTMLCommon, .jp-RenderedMarkdown {
        font-family: "Times New Roman", Times, serif !important;
        color: black !important;
        font-feature-settings: "kern" 1, "liga" 1, "clig" 1, "dlig" 1 !important;
        -webkit-font-smoothing: antialiased !important;
    }

    /* 2. MATNLAR: 1.5 oraliq, abzats va ro‘yxatlar */
    .rendered_html p, .jp-RenderedHTMLCommon p {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-align: justify !important;
        text-indent: 1.25cm !important; /* Faqat p uchun abzats */
        margin: 0 !important;
    }

    /* Ro‘yxatlar uchun maxsus (nuqtalarni qaytarish) */
    .rendered_html ul, .jp-RenderedHTMLCommon ul {
        list-style-type: disc !important;
        margin-left: 2.5cm !important; /* Nuqtalar ko‘rinishi uchun surish */
        padding: 0 !important;
        text-indent: 0 !important;
    }

    .rendered_html li, .jp-RenderedHTMLCommon li {
        display: list-item !important; /* Block-dan list-item-ga qaytarish */
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-indent: 0 !important;
        margin: 0 !important;
    }

    .rendered_html p, .jp-RenderedHTMLCommon p {
        text-indent: 1.25cm !important;
    }

    /* 3. SARLAVHALAR: Markazda */
    .rendered_html h1, .jp-RenderedHTMLCommon h1,
    .rendered_html h2, .jp-RenderedHTMLCommon h2,
    .rendered_html h3, .jp-RenderedHTMLCommon h3,
    .rendered_html h4, .jp-RenderedHTMLCommon h4 {
        font-family: "Times New Roman", Times, serif !important;
        text-align: center !important;
        text-indent: 0 !important;
        margin: 0.5em 0 !important;
        font-weight: bold !important;
    }
    
    /* 4. KOD BLOKLARI VA PROMPTLARNI (In/Out) YASHIRISH */
    :root {
        --jp-code-font-size: 12pt !important;
    }

    /* "In [ ]" va "Out [ ]" yozuvlarini butunlay yo‘qotish */
    .jp-InputPrompt, .jp-OutputPrompt, .prompt, .input_prompt, .output_prompt {
        display: none !important;
        width: 0 !important;
        visibility: hidden !important;
    }

    /* Kod bloklarini chap chekkaga taqash */
    .jp-CodeCell .jp-Cell-inputWrapper, .cell.code_cell .input {
        margin-left: 0 !important;
        padding-left: 0 !important;
    }

    /* Sliderni yo‘qotish va qatorni majburan sindirish */
    .jp-CodeMirror, .CodeMirror, .CodeMirror-scroll, .CodeMirror-sizer, .CodeMirror-lines,
    .jp-OutputArea-output pre, .output_area pre, 
    .CodeMirror-code, .CodeMirror-line,
    code, kbd, samp {
        font-family: "Consolas", monospace !important;
        font-size: 12pt !important;
        text-indent: 0 !important;
        line-height: 1.3 !important;
        white-space: pre-wrap !important;
        word-wrap: break-word !important;
        word-break: break-all !important;
        overflow-x: visible !important;
        height: auto !important;
    }

    /* 5. BIRINCHI KATAKCHANI YASHIRISH VA TANLANGANDA OCHISH */
    /* Odatiy holatda mutlaqo yashirin va umuman joy egallamaydi */
    .jp-Notebook .jp-Cell:first-child:not(.jp-mod-selected), 
    .container div.cell.code_cell:first-of-type:not(.selected) {
        position: absolute !important;
        height: 0 !important;
        min-height: 0 !important;
        width: 0 !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        overflow: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        visibility: hidden !important;
    }    

    /* Katakcha tanlanganda (Ctrl+A bosilganda) to‘liq ochiladi */
    .jp-Notebook .jp-Cell:first-child.jp-mod-selected,
    .container div.cell.code_cell:first-of-type.selected {
        position: relative !important;
        height: auto !important;
        width: 100% !important;
        opacity: 1 !important;
        overflow: visible !important;
        pointer-events: auto !important;
        visibility: visible !important;
    }
</style>
"""))

# Amaliy laboratoriya: DataFrame'da ma'lumotlarni tanlash

Taxminiy sarflanadigan vaqt: **30** daqiqa

## Maqsadlar

Ushbu laboratoriya ishini yakunlaganingizdan so'ng, siz quyidagilarni bajara olasiz:

* Pandas kutubxonasidan DataFrame va Series yaratishda foydalanish;
* `loc()` va `iloc()` funksiyalaridan foydalanib, DataFrame ichidagi ma'lumotlarning joylashuvini aniqlash;
* Slicing (kesish) usulidan foydalanish.

### **1-mashq: Pandas: DataFrame va Series**

**Pandas** — bu Python dasturlash tili asosida yaratilgan, ma’lumotlar tahlili uchun mo‘ljallangan mashhur kutubxonadir. Pandas ma’lumotlar bilan ishlash uchun asosan ikkita ma’lumot tuzilmasini taqdim etadi:

* DataFrame
* Series

**DataFrame** — bu ikki o‘lchamli ma’lumotlar tuzilmasi, ya’ni ma’lumotlar satrlar va ustunlar ko‘rinishida jadval shaklida joylashadi.

* Pandas DataFrame mavjud xotiradagi ma’lumotlar to‘plamini yuklash orqali yaratiladi.
* Ma’lumotlar manbasi SQL ma’lumotlar bazasi, CSV fayli, Excel fayli va h.k. bo‘lishi mumkin.
* Shuningdek, u ro‘yxatlar, lug‘atlar va lug‘atlar ro‘yxatidan ham yaratilishi mumkin.

**Series** — bu indekslangan ma’lumotlarning bir o‘lchamli massividir.
U ikkita asosiy komponentdan iborat:
1. Haqiqiy ma’lumotlar massivi.
2. Indekslar yoki ma’lumot yorliqlarining bog‘langan massivi.

Indeks alohida ma’lumot qiymatlariga kirish uchun ishlatiladi. Shuningdek, siz DataFrame-ning bitta ustunini **Series** sifatida ajratib olishingiz mumkin. Siz Pandas Series-ni bir o‘lchamli (1-D) DataFrame deb tasavvur qilishingiz mumkin.

In [24]:
# Keling, Pandas kutubxonasini import qilamiz
import pandas as pd

Pandas-ni import qilganingizdan so'ng, ma'lumotlarni yaratish va tahlil qilish uchun undagi o'rnatilgan funksiyalardan foydalanishingiz mumkin.

**Ushbu amaliy laboratoriya mashg'ulotida biz lug'at (dictionary) asosida DataFrame yaratishni o'rganamiz.**

Quyidagi kalitlar va qiymatlardan iborat 'x' lug'atini ko'rib chiqaylik.

So'ngra, `pd.DataFrame(dict)` funksiyasidan foydalanib, ushbu lug'atdan dataframe yaratamiz.

In [25]:
# 'x' lug'atini aniqlaymiz
x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

# lug'atni DataFrame-ga o'tkazamiz (casting)
df = pd.DataFrame(x)

# natijaviy df-ni ko'rsatamiz
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

Biz jadval bilan to‘g‘ridan-to‘g‘ri moslikni ko‘rishimiz mumkin. Kalitlar (keys) ustun nomlariga, qiymatlar yoki ro‘yxatlar (values/lists) esa satrlarga mos keladi.

#### Ustunni tanlash:

Pandas DataFrame-da ustunni tanlash uchun biz ustunlarga ularning nomi bilan murojaat qilishimiz mumkin.

Keling, `ID` ustunida mavjud bo‘lgan ma’lumotlarni chaqirib olamiz.

In [26]:
# "ID" ustunini ajratib olamiz va uni x o'zgaruvchisiga biriktiramiz
x = df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

Keling, `type()` funksiyasidan foydalanamiz va o‘zgaruvchining turini tekshiramiz.

In [27]:
# O'zgaruvchining turini tekshirish
type(x)

pandas.DataFrame

Chiqish natijasi bizga o‘zgaruvchining turi **DataFrame** obyekti ekanligini ko‘rsatadi.

#### Bir nechta ustunlarga kirish

Keling, `Department`, `Salary` va `ID` ustunlari uchun ma'lumotlarni ajratib olamiz.

In [28]:
# Bir nechta ustunlarni tanlash va ularni z o'zgaruvchisiga biriktirish
z = df[['Department', 'Salary', 'ID']]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

### O‘zingiz sinab ko‘ring

#### 1-muammo: Natijani quyidagidek ko‘rsatish uchun dataframe yarating:

<center>
    <img src="images/4.1. Student_data.png" width="300" alt="Student Data">
</center>

In [32]:
# kodingizni shu yerga yozing

<details><summary>Yechimni ko‘rish uchun bu yerga bosing</summary>

```python
a = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}
df1 = pd.DataFrame(a)
df1
    
```

</details>

#### 2-muammo: Marks ustunini ajratib oling va uni b o'zgaruvchisiga biriktiring

In [30]:
# kodingizni shu yerga yozing

<details><summary>Yechimni ko‘rish uchun bu yerga bosing</summary>

```python
b = df1[['Marks']]
b
    
```

</details>

#### 3-muammo: Country va Course ustunlarini ajratib oling va ularni c o'zgaruvchisiga biriktiring

In [31]:
# kodingizni shu yerga yozing

<details><summary>Yechimni ko‘rish uchun bu yerga bosing</summary>

```python
c = df1[['Country','Course']]
c
    
```

</details>

#### Ustunni Series ko‘rinishida ko‘rish uchun faqat bitta qavsdan foydalaning:

In [23]:
# Student ustunini Series obyekti sifatida olamiz

x = df1['Student']
x

NameError: name 'df1' is not defined

In [33]:
# x ning turini tekshiramiz
type(x)

pandas.DataFrame

Chiqish natijasi bizga o‘zgaruvchining turi **Series** obyekti ekanligini ko‘rsatadi.

### 2-mashq: `loc()` va `iloc()` funksiyalari

`loc()` — bu yorliqlarga (label) asoslangan ma'lumotlarni tanlash usuli bo'lib, u orqali biz tanlamoqchi bo'lgan satr yoki ustunning **nomini** ko'rsatishimiz kerak. Bu usul ko'rsatilgan diapazonning oxirgi elementini ham o'z ichiga oladi.

Tushunish uchun sodda sintaksis:

 - loc[satr_nomi, ustun_nomi]

`iloc()` — bu indekslarga (index) asoslangan tanlash usuli bo'lib, u orqali ma'lum bir satr yoki ustunni tanlash uchun **butun sonli indeksni** ko'rsatishimiz kerak. Bu usul ko'rsatilgan diapazonning oxirgi elementini o'z ichiga olmaydi.

Tushunish uchun sodda sintaksis:
   
 - iloc[satr_indeksi, ustun_indeksi]



<h4 id="data">Keling, bularga oid ba'zi misollarni ko'rib chiqamiz.</h4>

In [34]:
# Birinchi satr va birinchi ustundagi qiymatga kirish

df.iloc[0, 0]

'Rose'

In [35]:
# Birinchi satr va uchinchi ustundagi qiymatga kirish

df.iloc[0, 2]

'Architect Group'

In [36]:
# Ustun nomidan foydalanib qiymatga kirish

df.loc[0, 'Salary']

np.int64(100000)

Keling, ```df2``` deb nomlangan yangi dataframe yaratamiz va unga ```df``` ni biriktiramiz. Endi, `set_index()` metodi yordamida "Name" ustunini indeks ustuni sifatida o'rnatamiz.

In [37]:
df2=df
df2=df2.set_index("Name")

In [38]:
# Yangi dataframe-ning dastlabki 5 ta satrini ko'rsatish uchun
df2.head()

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [39]:
# Endi, ustun nomidan foydalanib ma'lumotga kiramiz
df2.loc['Jane', 'Salary']

np.int64(50000)

### O‘zingiz sinab ko‘ring

Yangi yaratilgan df2 dataframe-da Jane-ning bo'limini (Department) olish uchun `loc()` funksiyasidan foydalaning.

```python
# kodingizni shu yerga yozing
```

<details><summary>Yechimni ko‘rish uchun bu yerga bosing</summary>

```python
df2.loc['Jane', 'Department']
```

</details>

In [40]:
# kodingizni shu yerga yozing

<details><summary>Yechimni ko‘rish uchun bu yerga bosing</summary>

```python
df2.loc['Jane', 'Department']
```

</details>

Yangi yaratilgan df2 dataframe-da Mary-ning maoshini (Salary) olish uchun `iloc()` funksiyasidan foydalaning.

In [41]:
# kodingizni shu yerga yozing

<details><summary>Yechimni ko‘rish uchun bu yerga bosing</summary>

```python
df2.iloc[3,2]
    
```

</details>

### 3-mashq: Kesish (Slicing)

Kesish (Slicing) — DataFrame-dan ma'lum bir satrlar va/yoki ustunlar to'plamini tanlash uchun `[]` operatoridan foydalanadi.

Satrlar to'plamini kesib olish uchun quyidagi sintaksisdan foydalanasiz: `data[start:stop]`.

Bu yerda **start** (boshlanish) hisobga olinadigan indeksni, **stop** (to'xtash) esa siz tanlamoqchi bo'lgan satrdan KEYINGI bir qadamdagi indeksni anglatadi. Kesishni indeks orqali ham, ustun nomi orqali ham amalga oshirishingiz mumkin.

> **ESLATMA:** Pandas-da kesishda boshlang'ich chegara (`start`) natijaga kiritiladi.

Shunday qilib, agar siz 0, 1 va 2-satrlarni tanlamoqchi bo'lsangiz, kodingiz quyidagicha ko'rinadi: `df.iloc[0:3]`.

Bu Python-ga 0-indeksdan boshlashni va 0, 1, 2-satrlarni tanlashni, lekin 3-indeksni kiritmaslikni buyurayotganingizni anglatadi.

> **ESLATMA:** Yorliqlar (labels) DataFrame-da mavjud bo'lishi kerak, aks holda `KeyError` xatosini olasiz.

Yorliqlar bo'yicha indekslash (ya'ni `loc()` dan foydalanish) butun sonlar bo'yicha indekslashdan (ya'ni `iloc()` dan foydalanish) farq qiladi. `loc()` yordamida ham boshlang'ich, ham oxirgi chegara natijaga **kiritiladi**. `loc()` dan foydalanganda butun sonlarni ishlatish mumkin, lekin bu sonlar pozitsiyani emas, balki indeks yorlig'ini (nomini) anglatadi.

Masalan, `loc()` dan foydalanib `1:4` ni tanlash, `iloc()` yordamida `1:4` satrlarni tanlashdan farqli natija beradi.



<h4 id="data">Biz, shuningdek, DataFrame ichidagi satr va ustun joylashuvi hamda iloc indekslash yordamida aniq bir ma'lumot qiymatini tanlashimiz mumkin.</h4>

In [42]:
# keling, eski df dataframe-dan foydalanib kesishni (slicing) bajaramiz
df.iloc[0:2, 0:3]

   Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [43]:
# indeks ustuni 0, 1, 2 yorliqlariga ega bo'lgan eski df dataframe-da 
# loc() funksiyasi yordamida kesishni (slicing) bajaramiz
df.loc[0:2,'ID':'Department']

   ID       Department
0   1  Architect Group
1   2   Software Group
2   3      Design Team

In [44]:
# indeks ustuni Name bo'lgan va Rose, John hamda Jane yorliqlariga ega 
# yangi df2 dataframe-da loc() funksiyasi yordamida kesishni bajaramiz
df2.loc['Rose':'Jane', 'ID':'Department']

      ID       Department
Name
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team

<h2 id="quiz">O‘zingiz sinab ko‘ring</h2>

using `loc()` function, do slicing on old dataframe df to retrieve the Name, ID and department of index column having labels as 2,3

In [45]:
# Kodingizni pastga yozing va bajarish uchun Shift+Enter tugmalarini bosing

<details><summary>Yechimni ko‘rish uchun bu yerga bosing</summary>

```python
df.loc[2:3,'Name':'Department']
    
```

</details>

<h3 id="quiz">Tabriklaymiz, siz Pandas bo‘yicha ushbu darsni va amaliy laboratoriya ishini muvaffaqiyatli yakunladingiz.</h3>