In [42]:
from IPython.display import display, HTML

display(HTML("""
<style>
    /* 1. UMUMIY KONTEYNER VA SHRIFT */
    .rendered_html, .jp-RenderedHTMLCommon, .jp-RenderedMarkdown {
        font-family: "Times New Roman", Times, serif !important;
        color: black !important;
        font-feature-settings: "kern" 1, "liga" 1, "clig" 1, "dlig" 1 !important;
        -webkit-font-smoothing: antialiased !important;
    }

    /* 2. MATNLAR: 1.5 oraliq, abzats va ro‘yxatlar */
    .rendered_html p, .jp-RenderedHTMLCommon p {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-align: justify !important;
        text-indent: 1.25cm !important; /* Faqat p uchun abzats */
        margin: 0 !important;
    }

    /* Ro‘yxatlar uchun maxsus (nuqtalarni qaytarish) */
    .rendered_html ul, .jp-RenderedHTMLCommon ul {
        list-style-type: disc !important;
        margin-left: 2.5cm !important; /* Nuqtalar ko‘rinishi uchun surish */
        padding: 0 !important;
        text-indent: 0 !important;
    }

    .rendered_html li, .jp-RenderedHTMLCommon li {
        display: list-item !important; /* Block-dan list-item-ga qaytarish */
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-indent: 0 !important;
        margin: 0 !important;
    }

    .rendered_html p, .jp-RenderedHTMLCommon p {
        text-indent: 1.25cm !important;
    }

    /* 3. SARLAVHALAR: Markazda */
    .rendered_html h1, .jp-RenderedHTMLCommon h1,
    .rendered_html h2, .jp-RenderedHTMLCommon h2,
    .rendered_html h3, .jp-RenderedHTMLCommon h3,
    .rendered_html h4, .jp-RenderedHTMLCommon h4 {
        font-family: "Times New Roman", Times, serif !important;
        text-align: center !important;
        text-indent: 0 !important;
        margin: 0.5em 0 !important;
        font-weight: bold !important;
    }
    
    /* 4. KOD BLOKLARI VA PROMPTLARNI (In/Out) YASHIRISH */
    :root {
        --jp-code-font-size: 12pt !important;
    }

    /* "In [ ]" va "Out [ ]" yozuvlarini butunlay yo‘qotish */
    .jp-InputPrompt, .jp-OutputPrompt, .prompt, .input_prompt, .output_prompt {
        display: none !important;
        width: 0 !important;
        visibility: hidden !important;
    }

    /* Kod bloklarini chap chekkaga taqash */
    .jp-CodeCell .jp-Cell-inputWrapper, .cell.code_cell .input {
        margin-left: 0 !important;
        padding-left: 0 !important;
    }

    /* Sliderni yo‘qotish va qatorni majburan sindirish */
    .jp-CodeMirror, .CodeMirror, .CodeMirror-scroll, .CodeMirror-sizer, .CodeMirror-lines,
    .jp-OutputArea-output pre, .output_area pre, 
    .CodeMirror-code, .CodeMirror-line,
    code, kbd, samp {
        font-family: "Consolas", monospace !important;
        font-size: 12pt !important;
        text-indent: 0 !important;
        line-height: 1.3 !important;
        white-space: pre-wrap !important;
        word-wrap: break-word !important;
        word-break: break-all !important;
        overflow-x: visible !important;
        height: auto !important;
    }

    /* 5. BIRINCHI KATAKCHANI YASHIRISH VA TANLANGANDA OCHISH */
    /* Odatiy holatda mutlaqo yashirin va umuman joy egallamaydi */
    .jp-Notebook .jp-Cell:first-child:not(.jp-mod-selected), 
    .container div.cell.code_cell:first-of-type:not(.selected) {
        position: absolute !important;
        height: 0 !important;
        min-height: 0 !important;
        width: 0 !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        overflow: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        visibility: hidden !important;
    }    

    /* Katakcha tanlanganda (Ctrl+A bosilganda) to‘liq ochiladi */
    .jp-Notebook .jp-Cell:first-child.jp-mod-selected,
    .container div.cell.code_cell:first-of-type.selected {
        position: relative !important;
        height: auto !important;
        width: 100% !important;
        opacity: 1 !important;
        overflow: visible !important;
        pointer-events: auto !important;
        visibility: visible !important;
    }
</style>
"""))

# Amaliy Mashg'ulot: Pandas yordamida ma'lumotlarni yuklash

Taxminiy ketadigan vaqt: **30** daqiqa

## Maqsadlar

Ushbu laboratoriya ishini yakunlaganingizdan so'ng, quyidagilarni bajara olasiz:

* Ma'lumotlarga kirish va ularni ko'rish uchun Pandas kutubxonasidan foydalanish

<h2>Mundarija</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="#About-the-Dataset">Ma'lumotlar to'plami haqida</a></li>
        <li><a href="#Introduction-of-Pandas"><code>Pandas</code>ga kirish</a></li>
        <li><a href="#Viewing-Data-and-Accessing-Data">Ma'lumotlarni ko'rish va ularga kirish</a></li>
        <li><a href="#Quiz-on-DataFrame">DataFrame bo'yicha test</a></li>
    </ul>

</div>

<hr>

## Ma'lumotlar to'plami haqida

Jadvalda har bir albom uchun bitta satr va bir nechta ustunlar mavjud.

<ul>
    <li><b>artist</b>: Ijrochining ismi</li>
    <li><b>album</b>: Albom nomi</li>
    <li><b>released_year</b>: Albom chiqarilgan yil</li>
    <li><b>length_min_sec</b>: Albom davomiyligi (soat, daqiqa, soniya)</li>
    <li><b>genre</b>: Albom janri</li>
    <li><b>music_recording_sales_millions</b>: Musiqa yozuvi savdolari (AQSH dollarida million hisobida) <a href="http://www.song-database.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01">[SONG://DATABASE]</a> saytida </li>
    <li><b>claimed_sales_millions</b>: Albomning e'lon qilingan savdolari (AQSH dollarida million hisobida) <a href="http://www.song-database.com/">[SONG://DATABASE]</a> saytida</li>
    <li><b>date_released</b>: Albom chiqarilgan sana</li>
    <li><b>soundtrack</b>: Albom film saundtreki ekanligini ko'rsatadi (Y) yoki (N)</li>
    <li><b>rating_of_friends</b>: Do'stlaringiz tomonidan berilgan 1 dan 10 gacha bo'lgan reytingni ko'rsatadi</li>
</ul>

Ma'lumotlar to'plamini bu yerda ko'rishingiz mumkin:

<font size="1">
<table font-size:xx-small>
  <tr>
    <th>Artist</th>
    <th>Album</th> 
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th> 
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td> 
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td> 
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td> 
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td> 
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td> 
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td> 
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td> 
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td> 
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<hr>

## <code>Pandas</code>ga kirish

In [9]:
# Faylni o'rnatish uchun zarur bo'lgan bog'liqliklar

# Agar daftarni (notebook) o'z kompyuteringizda ishlatayotgan bo'lsangiz, aks holda buni izohda qoldiring
# !pip install xlrd

# !pip install openpyxl 
# import piplite
# await piplite.install(['xlrd','openpyxl'])

In [10]:
# Zarur kutubxonani import qilish
import pandas as pd

Import buyrug'idan so'ng, biz ko'plab tayyor klasslar va funksiyalardan foydalanish imkoniyatiga ega bo'lamiz. Bu kutubxona o'rnatilgan degan farazga asoslanadi; bizning laboratoriya muhitimizda barcha zarur kutubxonalar o'rnatilgan. Pandas ma'lumotlar bilan ishlashga ruxsat beradigan usullardan biri bu dataframe (ma'lumotlar freymi) hisoblanadi. Keling, vergul bilan ajratilgan qiymatlar (<b>.csv</b>) faylidan dataframe hosil qilish jarayonini ko'rib chiqaylik. Ushbu <code>csv_path</code> o'zgaruvchisi <b>.csv</b> faylning yo'lini saqlaydi va u <code>read_csv</code> funksiyasi uchun argument sifatida ishlatiladi. Natija <code>df</code> obyektida saqlanadi; bu Pandas dataframe'ga ishora qiluvchi o'zgaruvchi uchun ishlatiladigan umumiy qisqartma hisoblanadi.

In [43]:
# Read data from CSV file

# csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv'
# df = pd.read_csv(csv_path)

# from pyodide.http import pyfetch
# import pandas as pd

# filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv"

# async def download(url, filename):
#     response = await pyfetch(url)
#     if response.status == 200:
#         with open(filename, "wb") as f:
#             f.write(await response.bytes())


# await download(filename, "TopSellingAlbums.csv")
# df = pd.read_csv("TopSellingAlbums.csv")

> Eslatma: Laboratoriyaning ushbu versiyasi JupyterLite muhitida ishlaydi, bu esa ma'lumotlar to'plamini interfeysga yuklab olishni talab qiladi. Ushbu daftarning (notebook) yuklab olingan versiyasini o'z mahalliy kompyuterlarida ishlatayotgan o'quvchilar **yuqoridagi bosqichlarni o'tkazib yuborishlari** va shunchaki `pandas.read_csv()` funksiyasida URL manzilidan to'g'ridan-to'g'ri foydalanishlari mumkin. Quyidagi katakdagi (cell) buyruqlarni izohdan chiqarib, ishga tushirishingiz mumkin.

In [16]:
filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/TopSellingAlbums.csv"
df = pd.read_csv(filename)

Biz dataframe-ning dastlabki beshta satrini ko'zdan kechirish uchun `head()` metodidan foydalanishimiz mumkin:

In [17]:
# Dataframe'ning dastlabki beshta satrini chop etish

df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

Biz excel faylining yo'lini va <code>read_excel</code> funksiyasini ishlatamiz. Natija avvalgidek ma'lumotlar freymi (data frame) bo'ladi:

In [44]:
# # Excel faylidan ma'lumotlarni o'qish va dastlabki beshta satrni chop etish

# xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/jupyterlite/files/Module%205/data/TopSellingAlbums.xlsx'

# await download(xlsx_path, "TopSellingAlbums.xlsx")
# df = pd.read_excel("TopSellingAlbums.xlsx")
# df.head()

> Eslatma: Laboratoriyaning ushbu versiyasi JupyterLite muhitida ishlaydi, bu esa ma'lumotlar to'plamini interfeysga yuklab olishni talab qiladi. Ushbu daftarning (notebook) yuklab olingan versiyasini o'z mahalliy kompyuterlarida ishlatayotgan o'quvchilar **yuqoridagi bosqichlarni o'tkazib yuborishlari** va shunchaki `pandas.read_excel()` funksiyasida URL manzilidan to'g'ridan-to'g'ri foydalanishlari mumkin. Quyidagi katakdagi (cell) buyruqlarni izohdan chiqarib, ishga tushirishingiz mumkin.

In [19]:
xlsx_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/jupyterlite/files/Module%205/data/TopSellingAlbums.xlsx'
df = pd.read_excel(xlsx_path)
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,00:42:19,"pop, rock, R&B",46.0,65,1982-11-30,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,1980-07-25,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,1973-03-01,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,1977-10-21,NaN,8.0

Biz **Length** ustuniga murojaat qilishimiz va uni yangi **x** dataframe-ga biriktirishimiz mumkin:

In [20]:
# **Length** ustuniga murojaat qilish

x = df[['Length']]
x

     Length
0  00:42:19
1   0:42:11
2   0:42:49
3   0:57:44
4   0:46:33
5   0:43:08
6  01:15:54
7   0:40:01

Jarayon quyidagi rasmda ko'rsatilgan:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/DataEgOne.png" width="750">

<hr>

## Ma'lumotlarni ko'rish va ularga murojaat qilish

Siz, shuningdek, ustunni **series** (seriya) ko'rinishida ham olishingiz mumkin. Pandas seriyasini bir o'lchovli (1-D) dataframe deb tasavvur qilish mumkin. Buning uchun shunchaki bitta qavsdan foydalaning:

In [21]:
# Ustunni seriya (series) ko'rinishida olish

x = df['Length']
x

0    00:42:19
1     0:42:11
2     0:42:49
3     0:57:44
4     0:46:33
5     0:43:08
6    01:15:54
7     0:40:01
Name: Length, dtype: object

Siz, shuningdek, ustunni **dataframe** ko'rinishida ham olishingiz mumkin. Masalan, biz **Artist** ustunini biriktirishimiz mumkin:

In [22]:
# Ustunni dataframe ko'rinishida olish

x = df[['Artist']]
type(x)

pandas.DataFrame

Siz buni bir vaqtning o'zida bir nechta ustunlar uchun ham qilishingiz mumkin; buning uchun shunchaki dataframe nomini (bu holatda <code>df</code>) va qo'shaloq qavslar ichida bir nechta ustun sarlavhalari nomlarini yozish kifoya. Natijada ko'rsatilgan ustunlardan tashkil topgan yangi dataframe hosil bo'ladi:

In [23]:
# Bir nechta ustunlarga murojaat qilish

y = df[['Artist','Length','Genre']]
y

            Artist    Length                        Genre
0  Michael Jackson  00:42:19               pop, rock, R&B
1            AC/DC   0:42:11                    hard rock
2       Pink Floyd   0:42:49             progressive rock
3  Whitney Houston   0:57:44               R&B, soul, pop
4        Meat Loaf   0:46:33  hard rock, progressive rock
5           Eagles   0:43:08   rock, soft rock, folk rock
6         Bee Gees  01:15:54                        disco
7    Fleetwood Mac   0:40:01                    soft rock

Jarayon quyidagi rasmda ko'rsatilgan:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/images/DataEgTwo.png" width="1100">

Yagona elementlarga murojaat qilish usullaridan biri bu `iloc` metodidir. Bu metod yordamida 1-satr va 1-ustun elementini quyidagicha olishingiz mumkin:

In [25]:
# 1-satr va 1-ustundagi elementga murojaat qilish (indeks 0 dan boshlanadi)

df.iloc[0, 0]

'Michael Jackson'

Siz 2-satr va 1-ustun elementiga quyidagicha murojaat qilishingiz mumkin:

In [27]:
# 2-satr va 1-ustundagi elementga murojaat qilish

df.iloc[1, 0]

'AC/DC'

Siz 1-satr va 3-ustun elementiga quyidagicha murojaat qilishingiz mumkin:

In [28]:
# 1-satr va 3-ustundagi elementga murojaat qilish

df.iloc[0,2]

np.int64(1982)

In [29]:
# Ikkinchi satr va uchinchi ustundagi qiymatga murojaat qilish

df.iloc[1,2]

np.int64(1980)

Bu quyidagi rasmda ko'rsatilgan:

<img src="images/5.1. 2_loc.png" width="750">

Siz ustunga nomi orqali ham murojaat qilishingiz mumkin, quyidagilar yuqoridagilar bilan bir xil natijani beradi:

In [30]:
# Ustunga nomi orqali murojaat qilish

df.loc[1, 'Artist']

'AC/DC'

In [31]:
# Ustunga nomi orqali murojaat qilish

df.loc[1, 'Artist']

'AC/DC'

In [32]:
# Ustunga nomi orqali murojaat qilish

df.loc[0, 'Released']

np.int64(1982)

In [33]:
# Ustunga nomi orqali murojaat qilish

df.loc[1, 'Released']

np.int64(1980)

<img src="images/5.2. 1_loc.png" width="750">

Siz kesish (**slicing**) amalini ham indeks, ham ustun nomi orqali amalga oshirishingiz mumkin:

In [34]:
# Dataframeni kesish (slicing)

df.iloc[0:2, 0:3]

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

<img src="images/5.3. 4_loc.png" width="750">

In [35]:
# Dataframeni nomi orqali kesish (slicing)

df.loc[0:2, 'Artist':'Released']

            Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

<img src="images/5.4. 3_loc.png" width="750">

<hr>

## DataFrame bo'yicha test

Ustunni dataframe ko'rinishida saqlash uchun **Rating** ustunini qo'shaloq qavs ichida ko'rsatib, uni `q` o'zgaruvchisiga biriktiring:

In [36]:
# Kodni pastda yozing va bajarish uchun Shift+Enter tugmalarini bosing

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
q = df[['Rating']]
q
    
```

</details>

`Released` va `Artist` ustunlaridan tashkil topgan dataframe'ni `q` o'zgaruvchisiga biriktiring:

In [37]:
# Kodni pastda yozing va bajarish uchun Shift+Enter tugmalarini bosing

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
q = df[['Released', 'Artist']]
q
    
```

</details>

`df` ning 2-satr va 3-ustunidagi qiymatga murojaat qiling:

In [38]:
# Kodni pastda yozing va bajarish uchun Shift+Enter tugmalarini bosing

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
df.iloc[1, 2]
    
```

</details>

Quyidagi ro'yxatdan foydalanib, `df` dataframe indekslarini belgilarga o'zgartiring va uni `df_new` ga biriktiring; keyin `a` qatori va `'Artist'` ustuniga mos keluvchi elementni toping. So'ngra, `'Artist'` ustuni uchun `a` dan `d` gacha bo'lgan qatorlarni tanlang:

In [ ]:
new_index=['a','b','c','d','e','f','g','h']

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
df_new=df
df_new.index=new_index
df_new.loc['a', 'Artist']
df_new.loc['a':'d', 'Artist']
    
```

</details>

<hr>
<h2>Oxirgi mashq!</h2>
<p>Tabriklaymiz, siz Python bo'yicha birinchi darsingizni va amaliy laboratoriya mashg'ulotingizni yakunladingiz. 
<hr>

# Amaliy test: Pandas

### 1-Savol
**1. Ma'lumotlar freymiga (data frame) qaysi Python obyektini o'girasiz (cast)?**

* [ ] **A)** `tuple`
* [ ] **B)** `List`
* [ ] **C)** `Dictionary`
* [ ] **D)** `set`

---
<details>
<summary>To'g'ri javobni ko'rsat</summary>
<b>To'g'ri javob: C (Dictionary)</b> <br>
<i>Izoh: Pandas kutubxonasida lug'atning kalitlari (keys) odatda ustun nomlariga, undagi ro'yxatlar esa qator qiymatlariga aylanadi. Bu DataFrame yaratishning eng keng tarqalgan usullaridan biridir.</i>
</details>

### 2-Savol
**2. `df` DataFrame'ida birinchi qator va birinchi ustunga qanday murojaat qilasiz?**

* [ ] **A)** `df.iloc[1,0]`
* [ ] **B)** `df.iloc[1,1]`
* [ ] **C)** `df.iloc[0,0]`
* [ ] **D)** `df.iloc[0,1]`

---
<details>
<summary>To'g'ri javobni ko'rsat</summary>
<b>To'g'ri javob: C (df.iloc[0,0])</b> <br>
<i>Izoh: Pandasda (va Python'ning ko'plab boshqa kutubxonalarida) indekslash 0 dan boshlanadi. Shuning uchun birinchi qator 0-indeksda, birinchi ustun ham 0-indeksda joylashgan bo'ladi.</i>
</details>

### 3-Savol
**3. Pandas kutubxonasidan foydalangan holda CSV faylni yuklashning to'g'ri usuli qaysi?**

* [ ] **A)** `pandas.from_csv('data.csv')`
* [ ] **B)** `pandas.import_csv('data.csv')`
* [ ] **C)** `pandas.load_csv('data.csv')`
* [ ] **D)** `pandas.read_csv('data.csv')`

---
<details>
<summary>To'g'ri javobni ko'rsat</summary>
<b>To'g'ri javob: D (pandas.read_csv('data.csv'))</b> <br>
<i>Izoh: Pandasda fayllarni o'qish uchun mo'ljallangan funksiyalar har doim "read_" prefiksi bilan boshlanadi (masalan: read_csv, read_excel, read_json). `read_csv` eng ko'p ishlatiladigan funksiyalardan biri bo'lib, u tashqi ma'lumotlarni DataFrame formatiga o'tkazib beradi.</i>
</details>

### 4-Savol
**4. Faraz qiling, sizda turli musiqachilar, ularning mashhur albomlari va janrlari haqidagi ma'lumotlarni o'z ichiga olgan dataframe bor. Bu yerda `Genre` (Janr) ustuni ketma-ketlikda beshinchi ustun hisoblanadi va 7-qatorda "Disco" qiymati mavjud. Ushbu "Disco" qiymatini qanday tanlab olasiz?**

* [ ] **A)** `df.iloc[7, 'Genre']`
* [ ] **B)** `df.iloc[6, 4]`
* [ ] **C)** `df.iloc[6, 'genre']`
* [ ] **D)** `df.iloc[7, 5]`

---
<details>
<summary>To'g'ri javobni ko'rsat</summary>
<b>To'g'ri javob: B (df.iloc[6, 4])</b> <br>
<i>Izoh: Pandasda indekslash 0 dan boshlangani uchun:
1. 7-qatorning indeksi <b>6</b> bo'ladi ($7 - 1 = 6$).
2. 5-ustunning indeksi <b>4</b> bo'ladi ($5 - 1 = 4$).
Shuningdek, <code>iloc</code> metodi faqat butun sonli indekslar bilan ishlaydi (ustun nomlarini qabul qilmaydi).</i>
</details>

### 5-Savol
**5. Faraz qiling, sizda turli musiqachilar, ularning mashhur albomlari, janrlari va boshqa parametrlari ko'rsatilgan dataframe bor. Bu yerda `Album` ustuni ikkinchi ustun hisoblanadi. 3-qatordan 6-qatorgacha bo'lgan ma'lumotlarni (records) qanday qilib ajratib olamiz?**

* [ ] **A)** `df.loc[2:5, 1]`
* [ ] **B)** `df.loc[2:5, 'Album']`
* [ ] **C)** `df.loc[2, 'Album']`
* [ ] **D)** `df.iloc[2:6, 3]`

---
<details>
<summary>To'g'ri javobni ko'rsat</summary>
<b>To'g'ri javob: B (df.loc[2:5, 'Album'])</b> <br>
<i>Izoh: 
1. <b>loc</b> metodi yorliqlar (labels) bilan ishlaydi. 3-qatorning indeksi <b>2</b>, 6-qatorning indeksi esa <b>5</b> bo'ladi.
2. <b>loc</b> metodida slicing (kesish) amali oxirgi indeksni ham natijaga qo'shadi, ya'ni <code>2:5</code> yozuvi 2, 3, 4 va 5-indekslarni (jami 4 ta qator) qamrab oladi.
3. <code>'Album'</code> ustun nomi to'g'ridan-to'g'ri ko'rsatilgan.</i>
</details>